version: '3.8'

services:
  frontend:
    image: mackie86/ecommercereact:latest
    ports:
      - "3000:3000"  # Adjust the port if necessary
    depends_on:
      - backend

  backend:
    image: mackie86/ecommerce:latest
    ports:
      - "8080:8080"  # Adjust the port if necessary
    depends_on:
      - database
    environment:
      - DATASOURCE_CONNECTION_URL=jdbc:postgresql://ecommerce_database_1:5432/ecommerce
      - DATASOURCE_USERNAME=test1
      - DATASOURCE_PASSWORD=test1

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: test1
    ports:
      - "5432:5432"  # Adjust the port if necessary
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
